name: Commit Checker
on: [push]

jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r src/requirements.txt

    - name: Check for if quest is accepted
      id: check_accepted
      run: python src/Quests.py ${{ github.repository_owner }} check first_commit
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI}}
        GH_TOKEN: ${{ secrets.GH_TOKEN}}

    - name: Run commit checker
      if: steps.check_quest.outcome == 'success'
      run: python src/CommitChecker.py ${{ github.repository_owner }} ${{ github.repository }} ${{ github.ref_name }}
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI}}
        GH_TOKEN: ${{ secrets.GH_TOKEN}}
